#!/usr/bin/env bash
# Shared loop/review/audit exit code definitions.

EXIT_SUCCESS="${EXIT_SUCCESS:-0}"
EXIT_REVIEW_FAIL="${EXIT_REVIEW_FAIL:-2}"
EXIT_MISSING_TOKEN="${EXIT_MISSING_TOKEN:-3}"
EXIT_REVIEW_SELF_HEAL_EXHAUSTED="${EXIT_REVIEW_SELF_HEAL_EXHAUSTED:-4}"
EXIT_WATCHDOG="${EXIT_WATCHDOG:-5}"
EXIT_LOCK_CONFLICT="${EXIT_LOCK_CONFLICT:-6}"
EXIT_FINAL_GATE_EXHAUSTED="${EXIT_FINAL_GATE_EXHAUSTED:-7}"
EXIT_FINDINGS_PROCESSOR_FAILED="${EXIT_FINDINGS_PROCESSOR_FAILED:-8}"
EXIT_ARCH_REVIEW_EXHAUSTED="${EXIT_ARCH_REVIEW_EXHAUSTED:-9}"
EXIT_QUOTA_EXHAUSTED="${EXIT_QUOTA_EXHAUSTED:-10}"
EXIT_TIMEOUT="${EXIT_TIMEOUT:-11}"
EXIT_NO_OUTPUT_TIMEOUT="${EXIT_NO_OUTPUT_TIMEOUT:-12}"
EXIT_MODEL_POLICY_VIOLATION="${EXIT_MODEL_POLICY_VIOLATION:-13}"
EXIT_WRAPPER_NO_OUTPUT="${EXIT_WRAPPER_NO_OUTPUT:-125}"
